"""`agentix build` — build a deploy-ready bundle image.

Usage:

    agentix build primitives/bash                              # one namespace, auto-tag
    agentix build bash                                         # short name → primitives/bash
    agentix build primitives/bash -o my-bash:dev               # explicit tag
    agentix build bash files claude-code -o my-agent:0.1.0     # bundle several namespaces
    agentix build bash files --dry-run -o sandbox:dev          # stage to ./build/<tag>/

Each spec is one of:

  1. **Path:** a directory containing `pyproject.toml` and the namespace's
     Python package under `src/agentix/<name>/`.
  2. **Image ref:** a string with a `:` AND a `/` — pre-built (not yet wired).
  3. **Short name:** searched against `primitives/<name>/` in the repo,
     falling back to PyPI `agentix-<name>` (currently stubbed).

Build shape:

  Python deps are uniform: every namespace gets `pip install`ed into the
  runtime image's venv. System deps are optional — a namespace that needs
  native binaries (`claude` CLI, git, …) ships a `default.nix` next to its
  `pyproject.toml`. If any spec ships one, a Nix builder stage runs first;
  the resulting `/nix/store` is COPY'd into the final image so its binaries
  resolve at their content-addressed paths. Bundles with no `default.nix`
  files anywhere skip Nix entirely — `FROM python:slim` end to end.

  The output image extends `agentix/runtime:<framework-version>` (override
  via `--runtime-image`). The runtime image is built once from
  `primitives/_template/Dockerfile`; subsequent bundles reuse it.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from tempfile import TemporaryDirectory

from agentix import __version__ as FRAMEWORK_VERSION
from agentix.cli._resolve import REPO_ROOT, NamespaceSpec, read_pyproject, resolve_spec

_SOURCE_SKIP = {
    "__pycache__", ".venv", "build", "dist", ".git",
    ".pytest_cache", ".ruff_cache", ".mypy_cache",
}


def _derive_tag_from_pyproject(pyproject: dict) -> str:
    """`agentix-bash` v `0.1.0` → `agentix/bash:0.1.0`."""
    project = pyproject.get("project", {})
    name = project.get("name")
    version = project.get("version")
    if not isinstance(name, str) or not isinstance(version, str):
        raise SystemExit("pyproject.toml: [project] needs string name + version")
    if not name.startswith("agentix-"):
        raise SystemExit(
            f"pyproject.toml: name {name!r} must follow `agentix-<short>`"
        )
    return f"agentix/{name[len('agentix-'):]}:{version}"


def _resolve_path(spec: NamespaceSpec) -> Path:
    """Return the on-disk source dir for a spec; raise on unsupported kinds."""
    if spec.kind == "path":
        assert spec.path is not None
        return spec.path
    if spec.kind == "pypi":
        raise NotImplementedError(
            f"`agentix build {spec.short}`: PyPI sourcing not wired yet. "
            f"Needs a `pip download {spec.pypi_dist}` step before the source "
            f"dir is ready. Use a local path instead."
        )
    raise SystemExit(
        f"`agentix build {spec.short}`: image refs aren't a valid input — "
        f"that image already exists. Use `agentix deploy local --image {spec.image_ref}`."
    )


def _has_system_deps(src: Path) -> bool:
    """True if the namespace ships a `default.nix` next to its pyproject."""
    return (src / "default.nix").is_file()


def _stage(specs: list[tuple[NamespaceSpec, Path]], build_dir: Path) -> None:
    """Stage each namespace's project tree into `build_dir/<short>/`.

    The whole project dir is copied so pip can find pyproject.toml + src/,
    and Nix can find default.nix when it's present. Common dev artifacts
    (__pycache__, .venv, etc.) are skipped.
    """
    for spec, src in specs:
        dest = build_dir / spec.short
        dest.mkdir()
        for item in src.iterdir():
            if item.name in _SOURCE_SKIP or item.name.endswith(".egg-info"):
                continue
            d = dest / item.name
            if item.is_dir():
                shutil.copytree(item, d, ignore=shutil.ignore_patterns(*_SOURCE_SKIP))
            else:
                shutil.copy2(item, d)


def _render_dockerfile(
    specs: list[tuple[NamespaceSpec, Path]],
    runtime_image: str,
) -> str:
    """Multi-stage Dockerfile: optional Nix system-deps builder, then a
    final stage that extends the runtime image and pip-installs each
    staged namespace project.

    The Nix builder stage is omitted entirely when no namespace ships a
    `default.nix` — Python-only bundles skip nixos/nix altogether.
    """
    nix_specs = [(s, p) for s, p in specs if _has_system_deps(p)]

    parts: list[str] = ["# Generated by `agentix build`. Do not hand-edit."]

    if nix_specs:
        parts += [
            "ARG NIX_IMAGE=nixos/nix:latest",
            "",
            "FROM ${NIX_IMAGE} AS sys-builder",
            "RUN mkdir -p ~/.config/nix && \\",
            "    echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf && \\",
            "    nix-channel --update 2>/dev/null || true",
            "RUN mkdir -p /export/nix/store",
        ]
        for spec, _ in nix_specs:
            parts += [
                "",
                f"WORKDIR /src/{spec.short}",
                f"COPY {spec.short}/ ./",
                "RUN nix-build --no-out-link default.nix -o ./result && \\",
                "    STORE_PATH=$(readlink -f ./result) && \\",
                "    for p in $(nix-store -qR \"$STORE_PATH\"); do \\",
                "        cp -a \"$p\" /export/nix/store/ || true; \\",
                "    done",
            ]

    parts += ["", f"FROM {runtime_image}"]
    if nix_specs:
        parts.append("COPY --from=sys-builder /export/nix /nix")

    for spec, _ in specs:
        parts.append(f"COPY {spec.short}/ /src/{spec.short}/")
    install_paths = " ".join(f"/src/{s.short}" for s, _ in specs)
    parts.append(f"RUN pip install --no-cache-dir {install_paths}")

    short_names = " ".join(s.short for s, _ in specs)
    parts.append(f'LABEL org.agentix.bundle.namespaces="{short_names}"')

    return "\n".join(parts) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="agentix build",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "specs", nargs="+",
        help="one or more namespace short names, paths, or image refs",
    )
    parser.add_argument(
        "-o", "--output", "--tag", dest="output", default=None,
        help="output docker image tag. Required when building >1 namespace; "
             "auto-derived from pyproject for a single namespace.",
    )
    parser.add_argument(
        "--runtime-image", default=f"agentix/runtime:{FRAMEWORK_VERSION}",
        help="base runtime image the bundle extends (default: "
             f"agentix/runtime:{FRAMEWORK_VERSION})",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="stage to ./build/<tag>/ and print path; do NOT invoke docker",
    )
    args = parser.parse_args(argv)

    try:
        specs = [resolve_spec(s) for s in args.specs]
        shorts = [s.short for s in specs]
        dupes = {n for n in shorts if shorts.count(n) > 1}
        if dupes:
            raise SystemExit(f"duplicate namespace short names: {sorted(dupes)}")
        resolved = [(spec, _resolve_path(spec)) for spec in specs]
    except NotImplementedError as exc:
        raise SystemExit(f"error: {exc}") from exc

    if args.output:
        tag = args.output
    elif len(specs) == 1:
        tag = _derive_tag_from_pyproject(read_pyproject(resolved[0][1]))
    else:
        raise SystemExit("--output / --tag is required when building >1 namespace")

    if ":" not in tag:
        raise SystemExit(f"image tag must include `:<version>` (got {tag!r})")

    if args.dry_run:
        out = REPO_ROOT / "build" / tag.rsplit("/", 1)[-1].split(":", 1)[0]
        if out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True)
        _stage(resolved, out)
        (out / "Dockerfile").write_text(_render_dockerfile(resolved, args.runtime_image))
        print(f"staged build context → {out}")
        print(f"would build → {tag}")
        print(f"  extends → {args.runtime_image}")
        if len(specs) > 1:
            print(f"  namespaces: {', '.join(shorts)}")
        return 0

    with TemporaryDirectory(prefix="agentix-build-") as tmp:
        build_dir = Path(tmp)
        _stage(resolved, build_dir)
        (build_dir / "Dockerfile").write_text(_render_dockerfile(resolved, args.runtime_image))
        ns_count = len(specs)
        print(
            f"building {tag} ({ns_count} namespace{'s' if ns_count > 1 else ''} "
            f"extending {args.runtime_image})…",
            file=sys.stderr,
        )
        proc = subprocess.run(
            ["docker", "build", "-t", tag, str(build_dir)],
            check=False,
        )
        return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
