"""`agentix build` — package a Python project into a deploy-ready sandbox image.

Usage:

    agentix build                         # current directory's pyproject
    agentix build path/to/project         # explicit project root
    agentix build . -o my:0.1.0           # explicit image tag
    agentix build . --dry-run             # stage Dockerfile to ./build/<tag>/, no docker invoke

The single argument is a path to a directory containing `pyproject.toml`.
That project's `[project].dependencies` are the bundle's plugin set —
pip resolves them transitively, and the resulting wheels install into
the framework's venv at `/nix/runtime/`. At runtime, calls execute the
pickle-serialized callable payload. **Neither the CLI nor the user
enumerates plugins on the command line.**

Build shape:

  * **One pip install for the whole bundle.** Your project + every
    declared `agentix-*` dep + transitive deps install into a single
    /nix/runtime/ venv. Inline imports across plugins work as regular
    Python (`from agentix.bash import run` inside your worker resolves
    because bash is in the same site-packages).

  * **System binaries via Nix (optional).** If the project root carries
    a `default.nix`, a Nix builder stage runs first; the derivation's
    `bin/*` is symlinked into `/nix/runtime/bin/` so user code can
    `subprocess.run("git", …)` without absolute paths. Plugins that
    need their own system binaries are expected to declare them in the
    user's project `default.nix` for now.

The output image extends `agentix/runtime:<framework-version>` (override
via `--runtime-image`). That base image must already exist locally —
build it from `Agentix-Runtime-Basic/runtime/Dockerfile` or pull from
a registry.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from tempfile import TemporaryDirectory

from agentix import __version__ as FRAMEWORK_VERSION
from agentix.cli._resolve import REPO_ROOT, derive_tag, read_pyproject, short_name

_SOURCE_SKIP = {
    "__pycache__", ".venv", "build", "dist", ".git",
    ".pytest_cache", ".ruff_cache", ".mypy_cache",
}


def _has_system_deps(src: Path) -> bool:
    """True if the project ships a `default.nix` next to its pyproject."""
    return (src / "default.nix").is_file()


def _image_exists_locally(image: str) -> bool:
    """`docker image inspect` returns 0 iff the image is locally present."""
    proc = subprocess.run(
        ["docker", "image", "inspect", image],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    return proc.returncode == 0


def _ensure_runtime_image(runtime_image: str) -> None:
    """Verify the runtime base image exists locally.

    The Dockerfile ships with `agentix-runtime-basic`; users build it
    from that repo or pull it from a registry. The bundle build
    doesn't auto-build the base — making the user own that step keeps
    `agentix build`'s scope narrow.
    """
    if _image_exists_locally(runtime_image):
        return
    raise SystemExit(
        f"runtime image {runtime_image!r} not found locally. Build it from "
        f"Agentix-Runtime-Basic (`runtime/Dockerfile`) or pull it from your "
        f"registry, then re-run `agentix build`."
    )


def _stage(src: Path, build_dir: Path) -> None:
    """Copy the project tree into `build_dir/project/`, skipping caches."""
    dest = build_dir / "project"
    dest.mkdir()
    for item in src.iterdir():
        if item.name in _SOURCE_SKIP or item.name.endswith(".egg-info"):
            continue
        d = dest / item.name
        if item.is_dir():
            shutil.copytree(item, d, ignore=shutil.ignore_patterns(*_SOURCE_SKIP))
        else:
            shutil.copy2(item, d)


def _render_dockerfile(src: Path, runtime_image: str) -> str:
    """Generate the bundle's Dockerfile.

    Two stages, both optional in different ways:

      Stage 1 (Nix builder, only if project has `default.nix`): build
      the derivation, stash its closure + store-path so the next stage
      can symlink binaries.

      Stage 2 (final image): `FROM <runtime>`, copy the project source,
      one `pip install /src/project` to merge everything into
      `/nix/runtime/`. If a Nix derivation was built, symlink its
      `bin/*` into `/nix/runtime/bin/`.
    """
    has_nix = _has_system_deps(src)
    parts: list[str] = ["# Generated by `agentix build`. Do not hand-edit."]

    if has_nix:
        parts += [
            "ARG NIX_IMAGE=nixos/nix:latest",
            "",
            "FROM ${NIX_IMAGE} AS sys-builder",
            "RUN mkdir -p ~/.config/nix && \\",
            "    echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf && \\",
            "    nix-channel --update 2>/dev/null || true",
            "RUN mkdir -p /export/nix/store /export/nix/.sys-paths",
            "",
            "WORKDIR /src/project",
            "COPY project/ ./",
            "RUN nix-build --no-out-link default.nix -o ./result && \\",
            "    STORE_PATH=$(readlink -f ./result) && \\",
            "    for p in $(nix-store -qR \"$STORE_PATH\"); do \\",
            "        cp -a \"$p\" /export/nix/store/ || true; \\",
            "    done && \\",
            "    echo \"$STORE_PATH\" > /export/nix/.sys-paths/project",
        ]

    parts += ["", f"FROM {runtime_image}"]
    if has_nix:
        parts += [
            "COPY --from=sys-builder /export/nix/store /nix/store",
            "COPY --from=sys-builder /export/nix/.sys-paths /nix/.sys-paths",
        ]

    # Stage the source + install. Pip resolves the project's declared
    # deps (including transitive agentix-* plugins) into /nix/runtime/.
    parts += [
        "COPY project/ /src/project/",
        "RUN /nix/runtime/bin/pip install --no-cache-dir /src/project",
    ]
    if has_nix:
        parts += [
            "RUN SP=$(cat /nix/.sys-paths/project) && \\",
            "    for f in $SP/bin/*; do \\",
            "        ln -sf \"$f\" /nix/runtime/bin/$(basename \"$f\"); \\",
            "    done",
        ]
    return "\n".join(parts) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="agentix build",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "path", nargs="?", default=".",
        help="project root with pyproject.toml (default: current directory)",
    )
    parser.add_argument(
        "-o", "--output", "--tag", dest="output", default=None,
        help="output image tag. Defaults to <name>:<version> from pyproject.",
    )
    parser.add_argument(
        "--runtime-image", default=f"agentix/runtime:{FRAMEWORK_VERSION}",
        help="base runtime image. Must exist locally; build from "
             "Agentix-Runtime-Basic/runtime/Dockerfile or pull from your "
             f"registry. (default: agentix/runtime:{FRAMEWORK_VERSION})",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="stage Dockerfile to ./build/<tag>/; do not invoke docker",
    )
    args = parser.parse_args(argv)

    src = Path(args.path).resolve()
    if not src.is_dir():
        raise SystemExit(f"{src}: not a directory")
    pp = read_pyproject(src)

    tag = args.output or derive_tag(pp)
    if ":" not in tag:
        raise SystemExit(f"image tag must include `:<version>` (got {tag!r})")

    short = short_name(pp)

    if args.dry_run:
        out = REPO_ROOT / "build" / tag.rsplit("/", 1)[-1].split(":", 1)[0]
        if out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True)
        _stage(src, out)
        (out / "Dockerfile").write_text(_render_dockerfile(src, args.runtime_image))
        print(f"staged build context → {out}")
        print(f"would build → {tag}")
        print(f"  extends → {args.runtime_image}")
        print(f"  project → {short}")
        print(f"  nix derivation → {'yes' if _has_system_deps(src) else 'no'}")
        return 0

    _ensure_runtime_image(args.runtime_image)

    with TemporaryDirectory(prefix="agentix-build-") as tmp:
        build_dir = Path(tmp)
        _stage(src, build_dir)
        (build_dir / "Dockerfile").write_text(_render_dockerfile(src, args.runtime_image))
        print(
            f"building {tag} (project {short!r} extending {args.runtime_image})…",
            file=sys.stderr,
        )
        proc = subprocess.run(
            ["docker", "build", "-t", tag, str(build_dir)],
            check=False,
            stderr=subprocess.PIPE,
        )
        if proc.stderr:
            sys.stderr.buffer.write(proc.stderr)
        if proc.returncode != 0:
            err = proc.stderr.decode(errors="replace") if proc.stderr else ""
            if any(
                token in err
                for token in ("conflict", "no matching distribution", "incompatible", "ResolutionImpossible")
            ):
                print(
                    "\nhint: pip couldn't resolve the unified dep set. Pin a "
                    "compatible version pair across your `agentix-*` deps in "
                    "pyproject.toml, or split the conflicting plugins into "
                    "two bundles.",
                    file=sys.stderr,
                )
        return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
