"""`agentix install` — bundle multiple closures into a single image.

Usage:

    agentix install bash files claude-code -o my-agent:0.1.0
    agentix install ./primitives/bash ./my-agent  -o demo:dev
    agentix install bash files --dry-run          # stage to ./build/<tag>/

A bundle is one docker image carrying multiple closures' Python packages
+ native deps under a single `/nix/entry/` tree, with a `bundle.json`
discriminator so the runtime's `_auto_load` discovers every nested
closure on boot.

Spec resolution (per arg):

  1. **Path:** an existing directory containing `pyproject.toml` and an
     `agentix_closures/<name>/` package — used as-is.
  2. **Image ref:** a string with a `:` AND a `/` — treated as a
     pre-built closure image and pulled at bundle build time.
  3. **Short name:** searched against the framework's conventional
     extension roots — `primitives/<name>/`, `agents/<name>/`,
     `datasets/<name>/` (relative to the repo root). If none match,
     falls back to PyPI as `agentix-<kind>-<name>` for each kind.

Image-ref and PyPI paths aren't fully wired yet — they raise
NotImplementedError with a clear message. The local-path / short-name
case works end-to-end today, which covers the in-repo dev flow.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from tempfile import TemporaryDirectory

from agentix.cli._resolve import REPO_ROOT, ClosureSpec, resolve_spec

TEMPLATE_DIR = REPO_ROOT / "primitives" / "_template"


_SOURCE_SKIP = {
    "__pycache__", ".venv", "build", "dist", ".git",
    ".pytest_cache", ".ruff_cache", ".mypy_cache",
}


def _stage_bundle(
    bundle_name: str,
    bundle_version: str,
    specs: list[ClosureSpec],
    build_dir: Path,
) -> None:
    """Lay out a self-contained docker build context for the bundle.

    Layout:
      build_dir/
      ├── Dockerfile                       # generated, multi-stage build
      ├── gen_manifest.py                  # copied from tools/
      ├── default.nix                      # copied from primitives/_template/
      ├── bundle.json                      # baked into the final image
      └── <short>/                         # per-closure staging (the whole project)
          ├── pyproject.toml
          └── src/<pkg>/...                # or whatever the closure ships
    """
    # Per-closure source staging (path kind only at this stage).
    for spec in specs:
        if spec.kind != "path":
            # Image and PyPI paths require pulling artifacts before staging —
            # not wired yet. The Dockerfile generator below surfaces the same
            # error if we ever reach it.
            raise NotImplementedError(
                f"`agentix install {spec.short}`: {spec.kind} sourcing not "
                f"implemented yet. Use a local path or check that the closure "
                f"lives under primitives/, agents/, or datasets/ in this repo."
            )
        assert spec.path is not None
        sub = build_dir / spec.short
        sub.mkdir()
        for item in spec.path.iterdir():
            if item.name in _SOURCE_SKIP or item.name.endswith(".egg-info"):
                continue
            dest = sub / item.name
            if item.is_dir():
                shutil.copytree(item, dest, ignore=shutil.ignore_patterns(*_SOURCE_SKIP))
            else:
                shutil.copy2(item, dest)

    # Shared build infra — same default.nix used for single-closure builds.
    shutil.copy2(TEMPLATE_DIR / "default.nix", build_dir / "default.nix")

    # The bundle Dockerfile builds each closure's nix derivation in a
    # builder stage and pip-installs all of them into the final image. The
    # runtime's `_auto_load` walks `importlib.metadata.entry_points`, so as
    # long as every closure's wheel is installed, discovery works without
    # any extra disposition file.
    (build_dir / "Dockerfile").write_text(_render_dockerfile(specs))


def _render_dockerfile(specs: list[ClosureSpec]) -> str:
    builder_steps = "\n".join(
        f"WORKDIR /src/{spec.short}\n"
        f"COPY {spec.short}/ ./\n"
        f"COPY default.nix ./\n"
        f"RUN nix-build --no-out-link default.nix -o ./result && \\\n"
        f"    STORE_PATH=$(readlink -f ./result) && \\\n"
        f"    for p in $(nix-store -qR \"$STORE_PATH\"); do \\\n"
        f"        cp -a \"$p\" /export/nix/store/; \\\n"
        f"    done && \\\n"
        f"    mkdir -p /export/nix/entry/{spec.short} && \\\n"
        f"    cp -aL \"$STORE_PATH\"/* /export/nix/entry/{spec.short}/"
        for spec in specs
    )
    return f"""\
# Generated by `agentix install`. Do not hand-edit.
ARG NIX_IMAGE=nixos/nix:latest

FROM ${{NIX_IMAGE}} AS builder
RUN mkdir -p ~/.config/nix && \\
    echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf && \\
    nix-channel --update 2>/dev/null || true
RUN mkdir -p /export/nix/store /export/nix/entry

{builder_steps}

FROM busybox:stable
COPY --from=builder /export /
VOLUME /nix
LABEL org.agentix.closure=1
LABEL org.agentix.closure.kind=bundle
"""


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="agentix install",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("specs", nargs="+",
                        help="closure short names, paths, or image refs")
    parser.add_argument("-o", "--output", required=True,
                        help="bundle image tag, e.g. my-agent:0.1.0")
    parser.add_argument("--dry-run", action="store_true",
                        help="stage to ./build/<bundle>/ and print path; do NOT invoke docker")
    args = parser.parse_args(argv)

    if ":" not in args.output:
        raise SystemExit(f"--output must include a tag (got {args.output!r})")
    bundle_name, bundle_version = args.output.rsplit(":", 1)

    specs = [resolve_spec(s) for s in args.specs]
    # Validate uniqueness on `short` — same closure twice would collide
    # both in the build dir and at runtime registration.
    shorts = [s.short for s in specs]
    dupes = {n for n in shorts if shorts.count(n) > 1}
    if dupes:
        raise SystemExit(f"duplicate closure short names: {sorted(dupes)}")

    try:
        if args.dry_run:
            out = REPO_ROOT / "build" / bundle_name.rsplit("/", 1)[-1]
            if out.exists():
                shutil.rmtree(out)
            out.mkdir(parents=True)
            _stage_bundle(bundle_name, bundle_version, specs, out)
            print(f"staged bundle build context → {out}")
            print(f"would build → {args.output}")
            print(f"  closures: {', '.join(shorts)}")
            return 0

        with TemporaryDirectory(prefix="agentix-bundle-") as tmp:
            build_dir = Path(tmp)
            _stage_bundle(bundle_name, bundle_version, specs, build_dir)
            print(f"building {args.output}…", file=sys.stderr)
            proc = subprocess.run(
                ["docker", "build", "-t", args.output, str(build_dir)],
                check=False,
            )
            return proc.returncode
    except NotImplementedError as exc:
        # PyPI / image-ref sourcing are not wired yet — surface a clean
        # one-liner instead of a traceback.
        raise SystemExit(f"error: {exc}") from exc


if __name__ == "__main__":
    raise SystemExit(main())
